// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzWPoAPs-udBN2nSLTR5pdiPTpQB-SxZ8',
    appId: '1:1039404264673:web:7e7c3086b36cc027379ba0',
    messagingSenderId: '1039404264673',
    projectId: 'okwardrope',
    authDomain: 'okwardrope.firebaseapp.com',
    databaseURL: 'https://okwardrope-default-rtdb.firebaseio.com',
    storageBucket: 'okwardrope.firebasestorage.app',
    measurementId: 'G-NBQ2NQ013B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV0IV_7OWJeDllJUW8VE_KusZ6Elj7eyE',
    appId: '1:1039404264673:android:fa928d17561870e7379ba0',
    messagingSenderId: '1039404264673',
    projectId: 'okwardrope',
    databaseURL: 'https://okwardrope-default-rtdb.firebaseio.com',
    storageBucket: 'okwardrope.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN8_k59aayYaJ01GHO8oFafthYmATyQ3c',
    appId: '1:1039404264673:ios:186b66a67bf3b9a7379ba0',
    messagingSenderId: '1039404264673',
    projectId: 'okwardrope',
    databaseURL: 'https://okwardrope-default-rtdb.firebaseio.com',
    storageBucket: 'okwardrope.firebasestorage.app',
    iosBundleId: 'com.example.musicRoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN8_k59aayYaJ01GHO8oFafthYmATyQ3c',
    appId: '1:1039404264673:ios:186b66a67bf3b9a7379ba0',
    messagingSenderId: '1039404264673',
    projectId: 'okwardrope',
    databaseURL: 'https://okwardrope-default-rtdb.firebaseio.com',
    storageBucket: 'okwardrope.firebasestorage.app',
    iosBundleId: 'com.example.musicRoom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzWPoAPs-udBN2nSLTR5pdiPTpQB-SxZ8',
    appId: '1:1039404264673:web:8e15a6669433388e379ba0',
    messagingSenderId: '1039404264673',
    projectId: 'okwardrope',
    authDomain: 'okwardrope.firebaseapp.com',
    databaseURL: 'https://okwardrope-default-rtdb.firebaseio.com',
    storageBucket: 'okwardrope.firebasestorage.app',
    measurementId: 'G-23365ZBNBQ',
  );
}
